# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05afe045db33bac66d0a7c84c0113b1815c4a496071e1de270a70b3eae0e0b697efb465db8731ea121e959afa11e92e332bfb3f9f6a54c80a643682b4d971b6a

test:
  secret_key_base: 904ea104cec6a44e3d127a9aa89bab3d00f4c83a2915338e07b45984074836d403f460a26ef0af2e78c4e36c15a787062f3ac688e66994e87bde77f67a1acdd9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
